name: dish_dash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # A

  # C
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

  # D
  dio: ^5.7.0

  # F
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.3


  # G
  get_it: ^8.0.3
  json_annotation: ^4.9.0

  # I
  icons_launcher: ^3.0.0
  # L
  lottie: ^3.3.0


  dartz: ^0.10.1
  flutter_overboard: ^3.1.3
  curved_navigation_bar: ^1.0.6
  youtube_player_flutter: ^9.1.1
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # S
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  share_plus: ^10.1.3


icons_launcher:
  image_path: "assets/images/icon.png"
  package_name: Dish Dash

  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/fonts/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Dancing
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
    - family: lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Bold.ttf
          weight: 800
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300