// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoyfrTLTG7xakLsHGGipYP8XeJ_ypps0',
    appId: '1:933661360187:web:2f7de497a2b556ffb11c1e',
    messagingSenderId: '933661360187',
    projectId: 'dash-dish-7e52e',
    authDomain: 'dash-dish-7e52e.firebaseapp.com',
    storageBucket: 'dash-dish-7e52e.appspot.com',
    measurementId: 'G-H9FJHTDJVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqB46gLlw77YRdXaSLs_9Mq6bbhOxC4s',
    appId: '1:933661360187:android:479115bc94578688b11c1e',
    messagingSenderId: '933661360187',
    projectId: 'dash-dish-7e52e',
    storageBucket: 'dash-dish-7e52e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbS4_RGyB03snVSzJ6oCKGz3_YSxKvkg',
    appId: '1:933661360187:ios:3012abd3f2e20ca2b11c1e',
    messagingSenderId: '933661360187',
    projectId: 'dash-dish-7e52e',
    storageBucket: 'dash-dish-7e52e.appspot.com',
    iosBundleId: 'com.example.dishDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbS4_RGyB03snVSzJ6oCKGz3_YSxKvkg',
    appId: '1:933661360187:ios:3012abd3f2e20ca2b11c1e',
    messagingSenderId: '933661360187',
    projectId: 'dash-dish-7e52e',
    storageBucket: 'dash-dish-7e52e.appspot.com',
    iosBundleId: 'com.example.dishDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZoyfrTLTG7xakLsHGGipYP8XeJ_ypps0',
    appId: '1:933661360187:web:117c865aea206edfb11c1e',
    messagingSenderId: '933661360187',
    projectId: 'dash-dish-7e52e',
    authDomain: 'dash-dish-7e52e.firebaseapp.com',
    storageBucket: 'dash-dish-7e52e.appspot.com',
    measurementId: 'G-TN2V0RLCHH',
  );

}